Import Libraries and Load Datasets

In [5]:
import pandas as pd
import numpy as np

In [6]:
customers = pd.read_csv(r"C:\Users\ADMIN\Downloads\Blinkit Dataset\blinkit_customers.csv")
orders = pd.read_csv(r"C:\Users\ADMIN\Downloads\Blinkit Dataset\blinkit_orders.csv")
order_items = pd.read_csv(r"C:\Users\ADMIN\Downloads\Blinkit Dataset\blinkit_order_items.csv")
products = pd.read_csv(r"C:\Users\ADMIN\Downloads\Blinkit Dataset\blinkit_products.csv")
marketing = pd.read_csv(r"C:\Users\ADMIN\Downloads\Blinkit Dataset\blinkit_marketing_performance.csv")
feedback = pd.read_csv(r"C:\Users\ADMIN\Downloads\Blinkit Dataset\blinkit_customer_feedback.csv")

Create working Copies

In [7]:
customers_clean = customers.copy()
orders_clean = orders.copy()
order_items_clean = order_items.copy()
products_clean = products.copy()
marketing_clean = marketing.copy()
feedback_clean = feedback.copy()

Handle Missing Values

In [12]:
marketing_clean.isnull().sum()

campaign_id          0
campaign_name        0
date                 0
target_audience      0
channel              0
impressions          0
clicks               0
conversions          0
spend                0
revenue_generated    0
roas                 0
dtype: int64

In [13]:
feedback_clean.isnull().sum()

feedback_id          0
order_id             0
customer_id          0
rating               0
feedback_text        0
feedback_category    0
sentiment            0
feedback_date        0
dtype: int64

Remove Duplicate Records

In [14]:
customers_clean.duplicated().sum()

np.int64(0)

In [15]:
orders_clean.duplicated().sum()

np.int64(0)

In [16]:
order_items_clean.duplicated().sum()

np.int64(0)

In [17]:
products_clean.duplicated().sum()

np.int64(0)

In [18]:
marketing_clean.duplicated().sum()

np.int64(0)

In [19]:
feedback_clean.duplicated().sum()

np.int64(0)

In [20]:
customers_clean['customer_id'].duplicated().sum()

np.int64(0)

In [21]:
orders_clean['order_id'].duplicated().sum()

np.int64(0)

In [22]:
products_clean['product_id'].duplicated().sum()

np.int64(0)

Fix Data Types

In [24]:
print(customers_clean.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        2500 non-null   int64
 1   customer_name      2500 non-null   object
 2   email              2500 non-null   object
 3   phone              2500 non-null   int64
 4   address            2500 non-null   object
 5   area               2500 non-null   object
 6   pincode            2500 non-null   int64
 7   registration_date  2500 non-null   object
 8   customer_segment   2500 non-null   object
 9   total_orders       2500 non-null   int64
 10  avg_order_value    2500 non-null   float64
dtypes: float64(1), int64(4), object(6)
memory usage: 215.0+ KB
None

In [32]:
customers_clean['registration_date'] = pd.to_datetime(customers_clean['registration_date'])

In [33]:
print(customers_clean.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        2500 non-null   int64
 1   customer_name      2500 non-null   object
 2   email              2500 non-null   object
 3   phone              2500 non-null   int64
 4   address            2500 non-null   object
 5   area               2500 non-null   object
 6   pincode            2500 non-null   int64
 7   registration_date  2500 non-null   datetime64[ns]
 8   customer_segment   2500 non-null   object
 9   total_orders       2500 non-null   int64
 10  avg_order_value    2500 non-null   float64
dtypes: datetime64[ns](1), float64(1), int64(4), object(5)
memory usage: 215.0+ KB
None

In [34]:
print(orders_clean.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   order_id                5000 non-null   int64
 1   customer_id             5000 non-null   int64
 2   order_date              5000 non-null   object
 3   promised_delivery_time  5000 non-null   object
 4   actual_delivery_time    5000 non-null   object
 5   delivery_status         5000 non-null   object
 6   order_total             5000 non-null   float64
 7   payment_method          5000 non-null   object
 8   delivery_partner_id     5000 non-null   int64
 9   store_id                5000 non-null   int64
dtypes: float64(1), int64(4), object(5)
memory usage: 390.8+ KB
None

In [36]:
orders_clean['order_date'] = pd.to_datetime(orders_clean['order_date'])

In [37]:
orders_clean['promised_delivery_time'] = pd.to_datetime(orders_clean['promised_delivery_time'])

In [38]:
orders_clean['actual_delivery_time'] = pd.to_datetime(orders_clean['actual_delivery_time'])

In [39]:
print(orders_clean.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   order_id                5000 non-null   int64
 1   customer_id             5000 non-null   int64
 2   order_date              5000 non-null   datetime64[ns]
 3   promised_delivery_time  5000 non-null   datetime64[ns]
 4   actual_delivery_time    5000 non-null   datetime64[ns]
 5   delivery_status         5000 non-null   object
 6   order_total             5000 non-null   float64
 7   payment_method          5000 non-null   object
 8   delivery_partner_id     5000 non-null   int64
 9   store_id                5000 non-null   int64
dtypes: datetime64[ns](3), float64(1), int64(4), object(2)
memory usage: 390.8+ KB
None

In [40]:
print(order_items_clean.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    5000 non-null   int64
 1   product_id  5000 non-null   int64
 2   quantity    5000 non-null   int64
 3   unit_price  5000 non-null   float64
dtypes: float64(1), int64(3)
memory usage: 156.4 KB
None

In [41]:
print(products_clean.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268 entries, 0 to 267
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   product_id         268 non-null    int64
 1   product_name       268 non-null    object
 2   category           268 non-null    object
 3   brand              268 non-null    object
 4   price              268 non-null    float64
 5   mrp                268 non-null    float64
 6   margin_percentage  268 non-null    float64
 7   shelf_life_days    268 non-null    int64
 8   min_stock_level    268 non-null    int64
 9   max_stock_level    268 non-null    int64
dtypes: float64(3), int64(4), object(3)
memory usage: 21.1+ KB
None

In [42]:
print(marketing_clean.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5400 entries, 0 to 5399
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   campaign_id        5400 non-null   int64
 1   campaign_name      5400 non-null   object
 2   date               5400 non-null   object
 3   target_audience    5400 non-null   object
 4   channel            5400 non-null   object
 5   impressions        5400 non-null   int64
 6   clicks             5400 non-null   int64
 7   conversions        5400 non-null   int64
 8   spend              5400 non-null   float64
 9   revenue_generated  5400 non-null   float64
 10  roas               5400 non-null   float64
dtypes: float64(3), int64(4), object(4)
memory usage: 464.2+ KB
None

In [44]:
marketing_clean['date'] = pd.to_datetime(marketing_clean['date'])

In [45]:
print(marketing_clean.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5400 entries, 0 to 5399
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   campaign_id        5400 non-null   int64
 1   campaign_name      5400 non-null   object
 2   date               5400 non-null   datetime64[ns]
 3   target_audience    5400 non-null   object
 4   channel            5400 non-null   object
 5   impressions        5400 non-null   int64
 6   clicks             5400 non-null   int64
 7   conversions        5400 non-null   int64
 8   spend              5400 non-null   float64
 9   revenue_generated  5400 non-null   float64
 10  roas               5400 non-null   float64
dtypes: datetime64[ns](1), float64(3), int64(4), object(3)
memory usage: 464.2+ KB
None

In [46]:
print(feedback_clean.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   feedback_id        5000 non-null   int64
 1   order_id           5000 non-null   int64
 2   customer_id        5000 non-null   int64
 3   rating             5000 non-null   int64
 4   feedback_text      5000 non-null   object
 5   feedback_category  5000 non-null   object
 6   sentiment          5000 non-null   object
 7   feedback_date      5000 non-null   object
dtypes: int64(4), object(4)
memory usage: 312.6+ KB
None

In [48]:
feedback_clean['feedback_date'] = pd.to_datetime(feedback_clean['feedback_date'])

In [49]:
print(feedback_clean.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   feedback_id        5000 non-null   int64
 1   order_id           5000 non-null   int64
 2   customer_id        5000 non-null   int64
 3   rating             5000 non-null   int64
 4   feedback_text      5000 non-null   object
 5   feedback_category  5000 non-null   object
 6   sentiment          5000 non-null   object
 7   feedback_date      5000 non-null   datetime64[ns]
dtypes: datetime64[ns](1), int64(4), object(3)
memory usage: 312.6+ KB
None

Standardize Text

In [51]:
customers_clean['area'] = customers_clean['area'].str.strip()

In [52]:
customers_clean['customer_segment'] = customers_clean['customer_segment'].str.strip()

In [53]:
orders_clean['delivery_status'] = (orders_clean['delivery_status'].str.strip().str.title())

In [54]:
orders_clean['payment_method'] = (orders_clean['payment_method'].str.strip().str.title())

In [55]:
products_clean['category'] = (products_clean['category'].str.strip().str.title())

In [56]:
marketing_clean['target_audience'] = (marketing_clean['target_audience'].str.strip().str.title())

In [57]:
marketing_clean['channel'] = (marketing_clean['channel'].str.strip().str.title())

In [58]:
feedback_clean['sentiment'] = (feedback_clean['sentiment'].str.strip().str.title())

In [59]:
feedback_clean['feedback_category'] = (feedback_clean['feedback_category'].str.strip().str.title())

Validate Primary Keys

In [61]:
customers_clean['customer_id'].is_unique

True

In [62]:

orders_clean['order_id'].is_unique

True

In [63]:

products_clean['product_id'].is_unique

True

In [64]:
feedback_clean['feedback_id'].is_unique

True

Validate Foreign Keys

In [65]:
orders_clean[~orders_clean['customer_id'].isin(customers_clean['customer_id'])]

Empty DataFrame
Columns: [order_id, customer_id, order_date, promised_delivery_time, actual_delivery_time, delivery_status, order_total, payment_method, delivery_partner_id, store_id]
Index: []

In [66]:
order_items_clean[~order_items_clean['order_id'].isin(orders_clean['order_id'])]

Empty DataFrame
Columns: [order_id, product_id, quantity, unit_price]
Index: []

In [67]:
order_items_clean[~order_items_clean['product_id'].isin(products_clean['product_id'])]

Empty DataFrame
Columns: [order_id, product_id, quantity, unit_price]
Index: []

In [68]:
feedback_clean[~feedback_clean['order_id'].isin(orders_clean['order_id'])]

Empty DataFrame
Columns: [feedback_id, order_id, customer_id, rating, feedback_text, feedback_category, sentiment, feedback_date]
Index: []

Detect Invalid Values

In [69]:
products_clean[products_clean['price'] <= 0]

Empty DataFrame
Columns: [product_id, product_name, category, brand, price, mrp, margin_percentage, shelf_life_days, min_stock_level, max_stock_level]
Index: []

In [70]:
order_items_clean[order_items_clean['quantity'] <= 0]

Empty DataFrame
Columns: [order_id, product_id, quantity, unit_price]
Index: []

In [71]:
feedback_clean[~feedback_clean['rating'].between(1, 5)]

Empty DataFrame
Columns: [feedback_id, order_id, customer_id, rating, feedback_text, feedback_category, sentiment, feedback_date]
Index: []

Save the Cleaned Data

In [76]:
customers_clean.to_csv("customers_clean.csv", index = False)
orders_clean.to_csv("orders_clean.csv",index=False)
order_items_clean.to_csv("order_items_clean.csv",index=False)
products_clean.to_csv("products_clean.csv",index=False)
marketing_clean.to_csv("marketing_clean.csv",index=False)
feedback_clean.to_csv("feedback_clean.csv",index=False)