Load Cleaned Data

In [1]:
import pandas as pd
import numpy as np

customers = pd.read_csv("customers_clean.csv")
orders = pd.read_csv("orders_clean.csv")
order_items = pd.read_csv("order_items_clean.csv")
products = pd.read_csv("products_clean.csv")
marketing = pd.read_csv("marketing_clean.csv")
feedback = pd.read_csv("feedback_clean.csv")

Merge Datasets

In [2]:
customer_orders = pd.merge(customers,orders,how='left',on='customer_id')
customer_orders

,customer_id,customer_name,email,phone,address,area,pincode,registration_date,customer_segment,total_orders,avg_order_value,order_id,order_date,promised_delivery_time,actual_delivery_time,delivery_status,order_total,payment_method,delivery_partner_id,store_id
0,97475543,Niharika Nagi,ektataneja@example.org,912987579691,"23, Nayar Path, Bihar Sharif-154625",Udupi,321865,2023-05-13,Premium,13,451.92,1.002526e+09,2023-07-31 23:19:05,2023-07-31 23:29:05,2023-07-31 23:33:05,On Time,5001.82,Cash,56579.0,852.0
1,97475543,Niharika Nagi,ektataneja@example.org,912987579691,"23, Nayar Path, Bihar Sharif-154625",Udupi,321865,2023-05-13,Premium,13,451.92,4.928557e+09,2023-09-19 14:53:57,2023-09-19 15:11:57,2023-09-19 15:18:57,Slightly Delayed,2275.20,Card,49069.0,1415.0
2,97475543,Niharika Nagi,ektataneja@example.org,912987579691,"23, Nayar Path, Bihar Sharif-154625",Udupi,321865,2023-05-13,Premium,13,451.92,6.833977e+09,2023-06-05 04:44:35,2023-06-05 04:57:35,2023-06-05 05:22:35,Significantly Delayed,2495.74,Wallet,66274.0,9262.0
3,97475543,Niharika Nagi,ektataneja@example.org,912987579691,"23, Nayar Path, Bihar Sharif-154625",Udupi,321865,2023-05-13,Premium,13,451.92,7.147677e+09,2024-07-12 09:59:18,2024-07-12 10:09:18,2024-07-12 10:09:18,On Time,2543.15,Wallet,85980.0,4844.0
4,22077605,Megha Sachar,vedant45@example.com,915123179717,"51/302, Buch Chowk\nSrinagar-570271",Aligarh,149394,2024-06-18,Inactive,4,825.48,9.799231e+09,2024-03-07 08:59:56,2024-03-07 09:17:56,2024-03-07 09:21:56,On Time,872.83,Wallet,58378.0,7812.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5323,57392064,Lavanya Jain,deshpandeom@example.com,916137420258,"391, Edwin Path, Korba 202726",Udupi,688100,2024-06-23,Regular,4,1540.81,6.688079e+09,2024-04-18 12:12:45,2024-04-18 12:25:45,2024-04-18 12:23:45,On Time,53.49,Cash,94088.0,4812.0
5324,57392064,Lavanya Jain,deshpandeom@example.com,916137420258,"391, Edwin Path, Korba 202726",Udupi,688100,2024-06-23,Regular,4,1540.81,7.869105e+09,2023-10-01 21:30:39,2023-10-01 21:42:39,2023-10-01 21:41:39,On Time,1638.00,Cash,40351.0,5533.0
5325,71688530,Umang Dash,gokhalenicholas@example.org,917595275963,"151, Parmer Ganj\nLoni 906431",Kavali,528749,2024-03-18,Regular,1,1541.22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5326,89051578,Zinal Natarajan,vyasfrado@example.com,911994009448,"H.No. 172, Khanna Street, Pudukkottai 610564",Alwar,586734,2024-09-06,Premium,12,1185.50,6.947226e+09,2024-04-03 08:47:01,2024-04-03 08:58:01,2024-04-03 08:55:01,On Time,475.04,Cash,86451.0,7428.0
5327,78738569,Eiravati Sundaram,onkar24@example.com,914320353753,"H.No. 791, Sur Path\nBally 982559",Dewas,342448,2023-05-10,Inactive,4,376.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
customer_orders = customer_orders.merge(order_items,how='left',on='order_id')
customer_orders

,customer_id,customer_name,email,phone,address,area,pincode,registration_date,customer_segment,total_orders,...,promised_delivery_time,actual_delivery_time,delivery_status,order_total,payment_method,delivery_partner_id,store_id,product_id,quantity,unit_price
0,97475543,Niharika Nagi,ektataneja@example.org,912987579691,"23, Nayar Path, Bihar Sharif-154625",Udupi,321865,2023-05-13,Premium,13,...,2023-07-31 23:29:05,2023-07-31 23:33:05,On Time,5001.82,Cash,56579.0,852.0,444361.0,2.0,822.63
1,97475543,Niharika Nagi,ektataneja@example.org,912987579691,"23, Nayar Path, Bihar Sharif-154625",Udupi,321865,2023-05-13,Premium,13,...,2023-09-19 15:11:57,2023-09-19 15:18:57,Slightly Delayed,2275.20,Card,49069.0,1415.0,589812.0,2.0,163.03
2,97475543,Niharika Nagi,ektataneja@example.org,912987579691,"23, Nayar Path, Bihar Sharif-154625",Udupi,321865,2023-05-13,Premium,13,...,2023-06-05 04:57:35,2023-06-05 05:22:35,Significantly Delayed,2495.74,Wallet,66274.0,9262.0,490602.0,3.0,549.47
3,97475543,Niharika Nagi,ektataneja@example.org,912987579691,"23, Nayar Path, Bihar Sharif-154625",Udupi,321865,2023-05-13,Premium,13,...,2024-07-12 10:09:18,2024-07-12 10:09:18,On Time,2543.15,Wallet,85980.0,4844.0,490939.0,1.0,80.25
4,22077605,Megha Sachar,vedant45@example.com,915123179717,"51/302, Buch Chowk\nSrinagar-570271",Aligarh,149394,2024-06-18,Inactive,4,...,2024-03-07 09:17:56,2024-03-07 09:21:56,On Time,872.83,Wallet,58378.0,7812.0,39154.0,3.0,946.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5323,57392064,Lavanya Jain,deshpandeom@example.com,916137420258,"391, Edwin Path, Korba 202726",Udupi,688100,2024-06-23,Regular,4,...,2024-04-18 12:25:45,2024-04-18 12:23:45,On Time,53.49,Cash,94088.0,4812.0,462526.0,2.0,449.97
5324,57392064,Lavanya Jain,deshpandeom@example.com,916137420258,"391, Edwin Path, Korba 202726",Udupi,688100,2024-06-23,Regular,4,...,2023-10-01 21:42:39,2023-10-01 21:41:39,On Time,1638.00,Cash,40351.0,5533.0,820973.0,1.0,114.52
5325,71688530,Umang Dash,gokhalenicholas@example.org,917595275963,"151, Parmer Ganj\nLoni 906431",Kavali,528749,2024-03-18,Regular,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5326,89051578,Zinal Natarajan,vyasfrado@example.com,911994009448,"H.No. 172, Khanna Street, Pudukkottai 610564",Alwar,586734,2024-09-06,Premium,12,...,2024-04-03 08:58:01,2024-04-03 08:55:01,On Time,475.04,Cash,86451.0,7428.0,34200.0,3.0,319.80
5327,78738569,Eiravati Sundaram,onkar24@example.com,914320353753,"H.No. 791, Sur Path\nBally 982559",Dewas,342448,2023-05-10,Inactive,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
customer_orders = customer_orders.merge(products,how='left',on='product_id')
customer_orders

,customer_id,customer_name,email,phone,address,area,pincode,registration_date,customer_segment,total_orders,...,unit_price,product_name,category,brand,price,mrp,margin_percentage,shelf_life_days,min_stock_level,max_stock_level
0,97475543,Niharika Nagi,ektataneja@example.org,912987579691,"23, Nayar Path, Bihar Sharif-154625",Udupi,321865,2023-05-13,Premium,13,...,822.63,Pain Reliever,Pharmacy,"Prakash, Bawa and Kale",822.63,1028.29,20.0,365.0,20.0,71.0
1,97475543,Niharika Nagi,ektataneja@example.org,912987579691,"23, Nayar Path, Bihar Sharif-154625",Udupi,321865,2023-05-13,Premium,13,...,163.03,Detergent,Household Care,Bir PLC,163.03,217.37,25.0,365.0,22.0,52.0
2,97475543,Niharika Nagi,ektataneja@example.org,912987579691,"23, Nayar Path, Bihar Sharif-154625",Udupi,321865,2023-05-13,Premium,13,...,549.47,Sugar,Grocery & Staples,Raghavan Inc,549.47,646.44,15.0,365.0,20.0,71.0
3,97475543,Niharika Nagi,ektataneja@example.org,912987579691,"23, Nayar Path, Bihar Sharif-154625",Udupi,321865,2023-05-13,Premium,13,...,80.25,Lotion,Personal Care,"Roy, Barad and De",80.25,123.46,35.0,365.0,12.0,67.0
4,22077605,Megha Sachar,vedant45@example.com,915123179717,"51/302, Buch Chowk\nSrinagar-570271",Aligarh,149394,2024-06-18,Inactive,4,...,946.86,Mangoes,Fruits & Vegetables,"Suresh, Bose and Bajwa",946.86,1262.48,25.0,3.0,21.0,84.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5323,57392064,Lavanya Jain,deshpandeom@example.com,916137420258,"391, Edwin Path, Korba 202726",Udupi,688100,2024-06-23,Regular,4,...,449.97,Curd,Dairy & Breakfast,Pau and Sons,449.97,562.46,20.0,7.0,25.0,69.0
5324,57392064,Lavanya Jain,deshpandeom@example.com,916137420258,"391, Edwin Path, Korba 202726",Udupi,688100,2024-06-23,Regular,4,...,114.52,Baby Wipes,Baby Care,Lall LLC,114.52,163.60,30.0,365.0,29.0,56.0
5325,71688530,Umang Dash,gokhalenicholas@example.org,917595275963,"151, Parmer Ganj\nLoni 906431",Kavali,528749,2024-03-18,Regular,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5326,89051578,Zinal Natarajan,vyasfrado@example.com,911994009448,"H.No. 172, Khanna Street, Pudukkottai 610564",Alwar,586734,2024-09-06,Premium,12,...,319.80,Lotion,Personal Care,Munshi-Grewal,319.80,492.00,35.0,365.0,19.0,75.0
5327,78738569,Eiravati Sundaram,onkar24@example.com,914320353753,"H.No. 791, Sur Path\nBally 982559",Dewas,342448,2023-05-10,Inactive,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
master_df = customer_orders.merge(feedback,how='left',on='order_id')
master_df

,customer_id_x,customer_name,email,phone,address,area,pincode,registration_date,customer_segment,total_orders,...,shelf_life_days,min_stock_level,max_stock_level,feedback_id,customer_id_y,rating,feedback_text,feedback_category,sentiment,feedback_date
0,97475543,Niharika Nagi,ektataneja@example.org,912987579691,"23, Nayar Path, Bihar Sharif-154625",Udupi,321865,2023-05-13,Premium,13,...,365.0,20.0,71.0,7546504.0,97475543.0,4.0,"Average experience, could improve.",Delivery,Neutral,2023-07-31
1,97475543,Niharika Nagi,ektataneja@example.org,912987579691,"23, Nayar Path, Bihar Sharif-154625",Udupi,321865,2023-05-13,Premium,13,...,365.0,22.0,52.0,6006567.0,97475543.0,4.0,Very fresh and well-packaged.,Delivery,Positive,2023-09-19
2,97475543,Niharika Nagi,ektataneja@example.org,912987579691,"23, Nayar Path, Bihar Sharif-154625",Udupi,321865,2023-05-13,Premium,13,...,365.0,20.0,71.0,9768226.0,97475543.0,3.0,Not worth the price I paid.,App Experience,Negative,2023-06-05
3,97475543,Niharika Nagi,ektataneja@example.org,912987579691,"23, Nayar Path, Bihar Sharif-154625",Udupi,321865,2023-05-13,Premium,13,...,365.0,12.0,67.0,8068149.0,97475543.0,1.0,Taste was not as expected.,Delivery,Negative,2024-07-12
4,22077605,Megha Sachar,vedant45@example.com,915123179717,"51/302, Buch Chowk\nSrinagar-570271",Aligarh,149394,2024-06-18,Inactive,4,...,3.0,21.0,84.0,4329893.0,22077605.0,4.0,"Nothing to complain about, but nothing excepti...",Customer Service,Neutral,2024-03-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5323,57392064,Lavanya Jain,deshpandeom@example.com,916137420258,"391, Edwin Path, Korba 202726",Udupi,688100,2024-06-23,Regular,4,...,7.0,25.0,69.0,1886083.0,57392064.0,1.0,The packaging was poor.,Product Quality,Negative,2024-04-18
5324,57392064,Lavanya Jain,deshpandeom@example.com,916137420258,"391, Edwin Path, Korba 202726",Udupi,688100,2024-06-23,Regular,4,...,365.0,29.0,56.0,8959158.0,57392064.0,4.0,"Nothing to complain about, but nothing excepti...",Product Quality,Neutral,2023-10-01
5325,71688530,Umang Dash,gokhalenicholas@example.org,917595275963,"151, Parmer Ganj\nLoni 906431",Kavali,528749,2024-03-18,Regular,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5326,89051578,Zinal Natarajan,vyasfrado@example.com,911994009448,"H.No. 172, Khanna Street, Pudukkottai 610564",Alwar,586734,2024-09-06,Premium,12,...,365.0,19.0,75.0,8726995.0,89051578.0,4.0,Items were in perfect condition.,Customer Service,Positive,2024-04-03
5327,78738569,Eiravati Sundaram,onkar24@example.com,914320353753,"H.No. 791, Sur Path\nBally 982559",Dewas,342448,2023-05-10,Inactive,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Customer Features

In [6]:
customers

,customer_id,customer_name,email,phone,address,area,pincode,registration_date,customer_segment,total_orders,avg_order_value
0,97475543,Niharika Nagi,ektataneja@example.org,912987579691,"23, Nayar Path, Bihar Sharif-154625",Udupi,321865,2023-05-13,Premium,13,451.92
1,22077605,Megha Sachar,vedant45@example.com,915123179717,"51/302, Buch Chowk\nSrinagar-570271",Aligarh,149394,2024-06-18,Inactive,4,825.48
2,47822591,Hema Bahri,samiazaan@example.com,910034076149,"941\nAnne Street, Darbhanga 186125",Begusarai,621411,2024-09-25,Regular,17,1969.81
3,79726146,Zaitra Vig,ishanvi87@example.org,916264232390,"43/94, Ghosh, Alappuzha 635655",Kozhikode,826054,2023-10-04,New,4,220.09
4,57102800,Januja Verma,atideshpande@example.org,917293526596,"06\nOm, Ambarnath 477463",Ichalkaranji,730539,2024-03-22,Inactive,14,578.14
...,...,...,...,...,...,...,...,...,...,...,...
2495,48002829,Daksh Mandal,varkeymohammed@example.com,919587731286,"28/42, Venkataraman Ganj, Kishanganj-360157",Mumbai,45238,2024-01-25,Inactive,17,754.33
2496,57392064,Lavanya Jain,deshpandeom@example.com,916137420258,"391, Edwin Path, Korba 202726",Udupi,688100,2024-06-23,Regular,4,1540.81
2497,71688530,Umang Dash,gokhalenicholas@example.org,917595275963,"151, Parmer Ganj\nLoni 906431",Kavali,528749,2024-03-18,Regular,1,1541.22
2498,89051578,Zinal Natarajan,vyasfrado@example.com,911994009448,"H.No. 172, Khanna Street, Pudukkottai 610564",Alwar,586734,2024-09-06,Premium,12,1185.50
2499,78738569,Eiravati Sundaram,onkar24@example.com,914320353753,"H.No. 791, Sur Path\nBally 982559",Dewas,342448,2023-05-10,Inactive,4,376.50

In [7]:
customers['CLV'] = (customers['total_orders']*customers['avg_order_value'])

In [8]:
customers['customer_type'] = np.where(customers['total_orders']>10,'VIP','Regular')

In [9]:
customers

,customer_id,customer_name,email,phone,address,area,pincode,registration_date,customer_segment,total_orders,avg_order_value,CLV,customer_type
0,97475543,Niharika Nagi,ektataneja@example.org,912987579691,"23, Nayar Path, Bihar Sharif-154625",Udupi,321865,2023-05-13,Premium,13,451.92,5874.96,VIP
1,22077605,Megha Sachar,vedant45@example.com,915123179717,"51/302, Buch Chowk\nSrinagar-570271",Aligarh,149394,2024-06-18,Inactive,4,825.48,3301.92,Regular
2,47822591,Hema Bahri,samiazaan@example.com,910034076149,"941\nAnne Street, Darbhanga 186125",Begusarai,621411,2024-09-25,Regular,17,1969.81,33486.77,VIP
3,79726146,Zaitra Vig,ishanvi87@example.org,916264232390,"43/94, Ghosh, Alappuzha 635655",Kozhikode,826054,2023-10-04,New,4,220.09,880.36,Regular
4,57102800,Januja Verma,atideshpande@example.org,917293526596,"06\nOm, Ambarnath 477463",Ichalkaranji,730539,2024-03-22,Inactive,14,578.14,8093.96,VIP
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,48002829,Daksh Mandal,varkeymohammed@example.com,919587731286,"28/42, Venkataraman Ganj, Kishanganj-360157",Mumbai,45238,2024-01-25,Inactive,17,754.33,12823.61,VIP
2496,57392064,Lavanya Jain,deshpandeom@example.com,916137420258,"391, Edwin Path, Korba 202726",Udupi,688100,2024-06-23,Regular,4,1540.81,6163.24,Regular
2497,71688530,Umang Dash,gokhalenicholas@example.org,917595275963,"151, Parmer Ganj\nLoni 906431",Kavali,528749,2024-03-18,Regular,1,1541.22,1541.22,Regular
2498,89051578,Zinal Natarajan,vyasfrado@example.com,911994009448,"H.No. 172, Khanna Street, Pudukkottai 610564",Alwar,586734,2024-09-06,Premium,12,1185.50,14226.00,VIP
2499,78738569,Eiravati Sundaram,onkar24@example.com,914320353753,"H.No. 791, Sur Path\nBally 982559",Dewas,342448,2023-05-10,Inactive,4,376.50,1506.00,Regular

Order Features

In [10]:
orders

,order_id,customer_id,order_date,promised_delivery_time,actual_delivery_time,delivery_status,order_total,payment_method,delivery_partner_id,store_id
0,1961864118,30065862,2024-07-17 08:34:01,2024-07-17 08:52:01,2024-07-17 08:47:01,On Time,3197.07,Cash,63230,4771
1,1549769649,9573071,2024-05-28 13:14:29,2024-05-28 13:25:29,2024-05-28 13:27:29,On Time,976.55,Cash,14983,7534
2,9185164487,45477575,2024-09-23 13:07:12,2024-09-23 13:25:12,2024-09-23 13:29:12,On Time,839.05,Upi,39859,9886
3,9644738826,88067569,2023-11-24 16:16:56,2023-11-24 16:34:56,2023-11-24 16:33:56,On Time,440.23,Card,61497,7917
4,5427684290,83298567,2023-11-20 05:00:39,2023-11-20 05:17:39,2023-11-20 05:18:39,On Time,2526.68,Cash,84315,2741
...,...,...,...,...,...,...,...,...,...,...
4995,1669690997,62600289,2023-12-25 15:46:20,2023-12-25 16:05:20,2023-12-25 16:10:20,On Time,1132.33,Cash,90914,1587
4996,8340761903,53640286,2023-11-27 09:18:43,2023-11-27 09:38:43,2023-11-27 09:36:43,On Time,2372.01,Cash,27952,3458
4997,5936301790,87059497,2024-06-21 19:09:09,2024-06-21 19:23:09,2024-06-21 19:26:09,On Time,3158.35,Cash,9590,7424
4998,5710579377,67310893,2024-06-06 14:58:13,2024-06-06 15:12:13,2024-06-06 15:10:13,On Time,1918.92,Upi,29940,6128
4999,2494813730,28663279,2023-08-23 12:04:18,2023-08-23 12:20:18,2023-08-23 12:21:18,On Time,1879.46,Card,32851,5588

In [12]:
orders['Delivery_Delay_Minutes'] = (pd.to_datetime(orders['actual_delivery_time'])-pd.to_datetime(orders['promised_delivery_time'])).dt.total_seconds()/60

In [13]:
orders['Late_Delivery_Flag'] = np.where(orders['Delivery_Delay_Minutes']>0,1,0)

In [16]:
orders['Order_size'] = pd.cut(orders['order_total'],bins=[0,500,1000,2000,100000],labels=['Small','Medium','Large','Premium'])

In [17]:
orders

,order_id,customer_id,order_date,promised_delivery_time,actual_delivery_time,delivery_status,order_total,payment_method,delivery_partner_id,store_id,Delivery_Delay_Minutes,Late_Delivery_Flag,Order_size
0,1961864118,30065862,2024-07-17 08:34:01,2024-07-17 08:52:01,2024-07-17 08:47:01,On Time,3197.07,Cash,63230,4771,-5.0,0,Premium
1,1549769649,9573071,2024-05-28 13:14:29,2024-05-28 13:25:29,2024-05-28 13:27:29,On Time,976.55,Cash,14983,7534,2.0,1,Medium
2,9185164487,45477575,2024-09-23 13:07:12,2024-09-23 13:25:12,2024-09-23 13:29:12,On Time,839.05,Upi,39859,9886,4.0,1,Medium
3,9644738826,88067569,2023-11-24 16:16:56,2023-11-24 16:34:56,2023-11-24 16:33:56,On Time,440.23,Card,61497,7917,-1.0,0,Small
4,5427684290,83298567,2023-11-20 05:00:39,2023-11-20 05:17:39,2023-11-20 05:18:39,On Time,2526.68,Cash,84315,2741,1.0,1,Premium
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,1669690997,62600289,2023-12-25 15:46:20,2023-12-25 16:05:20,2023-12-25 16:10:20,On Time,1132.33,Cash,90914,1587,5.0,1,Large
4996,8340761903,53640286,2023-11-27 09:18:43,2023-11-27 09:38:43,2023-11-27 09:36:43,On Time,2372.01,Cash,27952,3458,-2.0,0,Premium
4997,5936301790,87059497,2024-06-21 19:09:09,2024-06-21 19:23:09,2024-06-21 19:26:09,On Time,3158.35,Cash,9590,7424,3.0,1,Premium
4998,5710579377,67310893,2024-06-06 14:58:13,2024-06-06 15:12:13,2024-06-06 15:10:13,On Time,1918.92,Upi,29940,6128,-2.0,0,Large
4999,2494813730,28663279,2023-08-23 12:04:18,2023-08-23 12:20:18,2023-08-23 12:21:18,On Time,1879.46,Card,32851,5588,1.0,1,Large

In [18]:
order_items

        order_id  product_id  quantity  unit_price
0     1961864118      642612         3      517.03
1     1549769649      378676         1      881.42
2     9185164487      741341         2      923.84
3     9644738826      561860         1      874.78
4     5427684290      602241         2      976.55
...          ...         ...       ...         ...
4995  1669690997      925482         3      475.04
4996  8340761903      124290         2       39.65
4997  5936301790      491314         3      973.44
4998  5710579377      319388         2      657.80
4999  2494813730      136533         1      826.21

[5000 rows x 4 columns]

In [19]:
order_items['Revenue'] = (order_items['quantity']*order_items['unit_price'])

In [20]:
order_items

        order_id  product_id  quantity  unit_price  Revenue
0     1961864118      642612         3      517.03  1551.09
1     1549769649      378676         1      881.42   881.42
2     9185164487      741341         2      923.84  1847.68
3     9644738826      561860         1      874.78   874.78
4     5427684290      602241         2      976.55  1953.10
...          ...         ...       ...         ...      ...
4995  1669690997      925482         3      475.04  1425.12
4996  8340761903      124290         2       39.65    79.30
4997  5936301790      491314         3      973.44  2920.32
4998  5710579377      319388         2      657.80  1315.60
4999  2494813730      136533         1      826.21   826.21

[5000 rows x 5 columns]

Product Features

In [21]:
products

,product_id,product_name,category,brand,price,mrp,margin_percentage,shelf_life_days,min_stock_level,max_stock_level
0,153019,Onions,Fruits & Vegetables,Aurora LLC,947.95,1263.93,25.0,3,13,88
1,11422,Potatoes,Fruits & Vegetables,Ramaswamy-Tata,127.16,169.55,25.0,3,20,65
2,669378,Potatoes,Fruits & Vegetables,Chadha and Sons,212.14,282.85,25.0,3,23,70
3,848226,Tomatoes,Fruits & Vegetables,Barad and Sons,209.59,279.45,25.0,3,10,51
4,890623,Onions,Fruits & Vegetables,"Sangha, Nagar and Varty",354.52,472.69,25.0,3,27,55
...,...,...,...,...,...,...,...,...,...,...
263,444361,Pain Reliever,Pharmacy,"Prakash, Bawa and Kale",822.63,1028.29,20.0,365,20,71
264,679284,Cough Syrup,Pharmacy,Pant LLC,877.89,1097.36,20.0,365,28,95
265,240179,Cough Syrup,Pharmacy,Ram-Suri,90.56,113.20,20.0,365,20,56
266,673058,Cough Syrup,Pharmacy,Balan-Madan,765.76,957.20,20.0,365,30,94
267,114414,Vitamins,Pharmacy,Kara-Golla,832.06,1040.07,20.0,365,26,66

In [22]:
products['Discount'] = (products['mrp']-products['price'])

In [23]:
products['Discount_Percentage'] = (products['Discount']/products['mrp'])*100

In [24]:
products['Price_Category'] = pd.cut(products['price'],bins=[0,300,500,700,5000],labels=['Low','Medium','High','Premium'])

In [25]:
products

,product_id,product_name,category,brand,price,mrp,margin_percentage,shelf_life_days,min_stock_level,max_stock_level,Discount,Discount_Percentage,Price_Category
0,153019,Onions,Fruits & Vegetables,Aurora LLC,947.95,1263.93,25.0,3,13,88,315.98,24.999802,Premium
1,11422,Potatoes,Fruits & Vegetables,Ramaswamy-Tata,127.16,169.55,25.0,3,20,65,42.39,25.001474,Low
2,669378,Potatoes,Fruits & Vegetables,Chadha and Sons,212.14,282.85,25.0,3,23,70,70.71,24.999116,Low
3,848226,Tomatoes,Fruits & Vegetables,Barad and Sons,209.59,279.45,25.0,3,10,51,69.86,24.999105,Low
4,890623,Onions,Fruits & Vegetables,"Sangha, Nagar and Varty",354.52,472.69,25.0,3,27,55,118.17,24.999471,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,444361,Pain Reliever,Pharmacy,"Prakash, Bawa and Kale",822.63,1028.29,20.0,365,20,71,205.66,20.000194,Premium
264,679284,Cough Syrup,Pharmacy,Pant LLC,877.89,1097.36,20.0,365,28,95,219.47,19.999818,Premium
265,240179,Cough Syrup,Pharmacy,Ram-Suri,90.56,113.20,20.0,365,20,56,22.64,20.000000,Low
266,673058,Cough Syrup,Pharmacy,Balan-Madan,765.76,957.20,20.0,365,30,94,191.44,20.000000,Premium
267,114414,Vitamins,Pharmacy,Kara-Golla,832.06,1040.07,20.0,365,26,66,208.01,19.999615,Premium

Feedback Features

In [26]:
feedback

,feedback_id,order_id,customer_id,rating,feedback_text,feedback_category,sentiment,feedback_date
0,2234710,1961864118,30065862,4,"It was okay, nothing special.",Delivery,Neutral,2024-07-17
1,5450964,1549769649,9573071,3,The order was incorrect.,App Experience,Negative,2024-05-28
2,482108,9185164487,45477575,3,"It was okay, nothing special.",App Experience,Neutral,2024-09-23
3,4823104,9644738826,88067569,4,The product met my expectations.,App Experience,Neutral,2023-11-24
4,3537464,5427684290,83298567,3,Product was damaged during delivery.,Delivery,Negative,2023-11-20
...,...,...,...,...,...,...,...,...
4995,9024060,1669690997,62600289,3,Taste was not as expected.,Product Quality,Negative,2023-12-25
4996,4715968,8340761903,53640286,3,"Average experience, could improve.",Product Quality,Neutral,2023-11-27
4997,9621021,5936301790,87059497,4,"Average experience, could improve.",App Experience,Neutral,2024-06-21
4998,1134095,5710579377,67310893,4,"Average experience, could improve.",Delivery,Neutral,2024-06-06
4999,6578433,2494813730,28663279,4,"It was okay, nothing special.",Customer Service,Neutral,2023-08-23

In [27]:
feedback['positive'] = np.where(feedback['rating']>=4,1,0)

In [28]:
feedback['negative'] = np.where(feedback['rating']<=2,1,0)

In [29]:
feedback['rating_category'] = pd.cut(feedback['rating'],bins=[0,2,3,5],labels=['Poor','Average','Excellent'])

In [30]:
feedback

,feedback_id,order_id,customer_id,rating,feedback_text,feedback_category,sentiment,feedback_date,positive,negative,rating_category
0,2234710,1961864118,30065862,4,"It was okay, nothing special.",Delivery,Neutral,2024-07-17,1,0,Excellent
1,5450964,1549769649,9573071,3,The order was incorrect.,App Experience,Negative,2024-05-28,0,0,Average
2,482108,9185164487,45477575,3,"It was okay, nothing special.",App Experience,Neutral,2024-09-23,0,0,Average
3,4823104,9644738826,88067569,4,The product met my expectations.,App Experience,Neutral,2023-11-24,1,0,Excellent
4,3537464,5427684290,83298567,3,Product was damaged during delivery.,Delivery,Negative,2023-11-20,0,0,Average
...,...,...,...,...,...,...,...,...,...,...,...
4995,9024060,1669690997,62600289,3,Taste was not as expected.,Product Quality,Negative,2023-12-25,0,0,Average
4996,4715968,8340761903,53640286,3,"Average experience, could improve.",Product Quality,Neutral,2023-11-27,0,0,Average
4997,9621021,5936301790,87059497,4,"Average experience, could improve.",App Experience,Neutral,2024-06-21,1,0,Excellent
4998,1134095,5710579377,67310893,4,"Average experience, could improve.",Delivery,Neutral,2024-06-06,1,0,Excellent
4999,6578433,2494813730,28663279,4,"It was okay, nothing special.",Customer Service,Neutral,2023-08-23,1,0,Excellent

Marketing Features

In [31]:
marketing

,campaign_id,campaign_name,date,target_audience,channel,impressions,clicks,conversions,spend,revenue_generated,roas
0,548299,New User Discount,2024-11-05,Premium,App,3130,163,78,1431.85,4777.75,3.60
1,390914,Weekend Special,2024-11-05,Inactive,App,3925,494,45,4506.34,6238.11,2.98
2,834385,Festival Offer,2024-11-05,Inactive,Email,7012,370,78,4524.23,2621.00,2.95
3,241523,Flash Sale,2024-11-05,Inactive,Sms,1115,579,86,3622.79,2955.00,2.84
4,595111,Membership Drive,2024-11-05,New Users,Email,7172,795,54,2888.99,8951.81,2.22
...,...,...,...,...,...,...,...,...,...,...,...
5395,381623,Membership Drive,2023-03-17,New Users,Email,8331,809,92,2363.07,3710.79,1.64
5396,493317,Category Promotion,2023-03-17,Premium,Social Media,5216,860,34,3922.53,7701.25,2.01
5397,879292,App Push Notification,2023-03-17,All,App,8480,734,20,1990.75,6650.41,3.98
5398,461129,Email Campaign,2023-03-17,New Users,Email,3569,568,10,4246.47,5880.42,2.50
5399,282514,Referral Program,2023-03-17,New Users,Social Media,5967,439,78,1511.93,8322.01,3.08

In [32]:
marketing['CTR'] = (marketing['clicks']/marketing['impressions'])*100

In [33]:
marketing['Conversion_rate'] = (marketing['conversions']/marketing['clicks'])*100

In [34]:
marketing['ROAS'] = (marketing['revenue_generated']/marketing['spend'])

In [35]:
marketing['Cost_per_Conversion'] = (marketing['spend']/marketing['conversions'])

In [37]:
marketing['Campaign_Profit'] = (marketing['revenue_generated']-marketing['spend'])

In [38]:
marketing

,campaign_id,campaign_name,date,target_audience,channel,impressions,clicks,conversions,spend,revenue_generated,roas,CTR,Conversion_rate,ROAS,Cost_per_Conversion,Campaign_Profit
0,548299,New User Discount,2024-11-05,Premium,App,3130,163,78,1431.85,4777.75,3.60,5.207668,47.852761,3.336767,18.357051,3345.90
1,390914,Weekend Special,2024-11-05,Inactive,App,3925,494,45,4506.34,6238.11,2.98,12.585987,9.109312,1.384296,100.140889,1731.77
2,834385,Festival Offer,2024-11-05,Inactive,Email,7012,370,78,4524.23,2621.00,2.95,5.276669,21.081081,0.579325,58.002949,-1903.23
3,241523,Flash Sale,2024-11-05,Inactive,Sms,1115,579,86,3622.79,2955.00,2.84,51.928251,14.853195,0.815670,42.125465,-667.79
4,595111,Membership Drive,2024-11-05,New Users,Email,7172,795,54,2888.99,8951.81,2.22,11.084774,6.792453,3.098595,53.499815,6062.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5395,381623,Membership Drive,2023-03-17,New Users,Email,8331,809,92,2363.07,3710.79,1.64,9.710719,11.372064,1.570326,25.685543,1347.72
5396,493317,Category Promotion,2023-03-17,Premium,Social Media,5216,860,34,3922.53,7701.25,2.01,16.487730,3.953488,1.963337,115.368529,3778.72
5397,879292,App Push Notification,2023-03-17,All,App,8480,734,20,1990.75,6650.41,3.98,8.655660,2.724796,3.340656,99.537500,4659.66
5398,461129,Email Campaign,2023-03-17,New Users,Email,3569,568,10,4246.47,5880.42,2.50,15.914822,1.760563,1.384778,424.647000,1633.95
5399,282514,Referral Program,2023-03-17,New Users,Social Media,5967,439,78,1511.93,8322.01,3.08,7.357131,17.767654,5.504230,19.383718,6810.08

Create Master Analytical Dataset

In [41]:
master_df = orders.merge(customers,on='customer_id',how='left')

In [42]:
master_df = master_df.merge(order_items,on='order_id',how='left')

In [43]:
master_df = master_df.merge(products,on='product_id',how='left')

In [44]:
master_df = master_df.merge(feedback,on='order_id',how='left')

In [45]:
master_df

,order_id,customer_id_x,order_date,promised_delivery_time,actual_delivery_time,delivery_status,order_total,payment_method,delivery_partner_id,store_id,...,feedback_id,customer_id_y,rating,feedback_text,feedback_category,sentiment,feedback_date,positive,negative,rating_category
0,1961864118,30065862,2024-07-17 08:34:01,2024-07-17 08:52:01,2024-07-17 08:47:01,On Time,3197.07,Cash,63230,4771,...,2234710,30065862,4,"It was okay, nothing special.",Delivery,Neutral,2024-07-17,1,0,Excellent
1,1549769649,9573071,2024-05-28 13:14:29,2024-05-28 13:25:29,2024-05-28 13:27:29,On Time,976.55,Cash,14983,7534,...,5450964,9573071,3,The order was incorrect.,App Experience,Negative,2024-05-28,0,0,Average
2,9185164487,45477575,2024-09-23 13:07:12,2024-09-23 13:25:12,2024-09-23 13:29:12,On Time,839.05,Upi,39859,9886,...,482108,45477575,3,"It was okay, nothing special.",App Experience,Neutral,2024-09-23,0,0,Average
3,9644738826,88067569,2023-11-24 16:16:56,2023-11-24 16:34:56,2023-11-24 16:33:56,On Time,440.23,Card,61497,7917,...,4823104,88067569,4,The product met my expectations.,App Experience,Neutral,2023-11-24,1,0,Excellent
4,5427684290,83298567,2023-11-20 05:00:39,2023-11-20 05:17:39,2023-11-20 05:18:39,On Time,2526.68,Cash,84315,2741,...,3537464,83298567,3,Product was damaged during delivery.,Delivery,Negative,2023-11-20,0,0,Average
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,1669690997,62600289,2023-12-25 15:46:20,2023-12-25 16:05:20,2023-12-25 16:10:20,On Time,1132.33,Cash,90914,1587,...,9024060,62600289,3,Taste was not as expected.,Product Quality,Negative,2023-12-25,0,0,Average
4996,8340761903,53640286,2023-11-27 09:18:43,2023-11-27 09:38:43,2023-11-27 09:36:43,On Time,2372.01,Cash,27952,3458,...,4715968,53640286,3,"Average experience, could improve.",Product Quality,Neutral,2023-11-27,0,0,Average
4997,5936301790,87059497,2024-06-21 19:09:09,2024-06-21 19:23:09,2024-06-21 19:26:09,On Time,3158.35,Cash,9590,7424,...,9621021,87059497,4,"Average experience, could improve.",App Experience,Neutral,2024-06-21,1,0,Excellent
4998,5710579377,67310893,2024-06-06 14:58:13,2024-06-06 15:12:13,2024-06-06 15:10:13,On Time,1918.92,Upi,29940,6128,...,1134095,67310893,4,"Average experience, could improve.",Delivery,Neutral,2024-06-06,1,0,Excellent
4999,2494813730,28663279,2023-08-23 12:04:18,2023-08-23 12:20:18,2023-08-23 12:21:18,On Time,1879.46,Card,32851,5588,...,6578433,28663279,4,"It was okay, nothing special.",Customer Service,Neutral,2023-08-23,1,0,Excellent

In [46]:
master_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 51 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   order_id                5000 non-null   int64
 1   customer_id_x           5000 non-null   int64
 2   order_date              5000 non-null   object
 3   promised_delivery_time  5000 non-null   object
 4   actual_delivery_time    5000 non-null   object
 5   delivery_status         5000 non-null   object
 6   order_total             5000 non-null   float64
 7   payment_method          5000 non-null   object
 8   delivery_partner_id     5000 non-null   int64
 9   store_id                5000 non-null   int64
 10  Delivery_Delay_Minutes  5000 non-null   float64
 11  Late_Delivery_Flag      5000 non-null   int64
 12  Order_size              5000 non-null   category
 13  customer_name           5000 non-null   object
 14  email                   5000 non-null   object
 15  phone                   5000 non-null   int64
 16  address                 5000 non-null   object
 17  area                    5000 non-null   object
 18  pincode                 5000 non-null   int64
 19  registration_date       5000 non-null   object
 20  customer_segment        5000 non-null   object
 21  total_orders            5000 non-null   int64
 22  avg_order_value         5000 non-null   float64
 23  CLV                     5000 non-null   float64
 24  customer_type           5000 non-null   object
 25  product_id              5000 non-null   int64
 26  quantity                5000 non-null   int64
 27  unit_price              5000 non-null   float64
 28  Revenue                 5000 non-null   float64
 29  product_name            5000 non-null   object
 30  category                5000 non-null   object
 31  brand                   5000 non-null   object
 32  price                   5000 non-null   float64
 33  mrp                     5000 non-null   float64
 34  margin_percentage       5000 non-null   float64
 35  shelf_life_days         5000 non-null   int64
 36  min_stock_level         5000 non-null   int64
 37  max_stock_level         5000 non-null   int64
 38  Discount                5000 non-null   float64
 39  Discount_Percentage     5000 non-null   float64
 40  Price_Category          5000 non-null   category
 41  feedback_id             5000 non-null   int64
 42  customer_id_y           5000 non-null   int64
 43  rating                  5000 non-null   int64
 44  feedback_text           5000 non-null   object
 45  feedback_category       5000 non-null   object
 46  sentiment               5000 non-null   object
 47  feedback_date           5000 non-null   object
 48  positive                5000 non-null   int64
 49  negative                5000 non-null   int64
 50  rating_category         5000 non-null   category
dtypes: category(3), float64(11), int64(18), object(19)
memory usage: 1.8+ MB

In [47]:
master_df.shape

(5000, 51)

Save Engineered Data

In [48]:
customers.to_csv("customers_features.csv",index=False)
orders.to_csv("orders_features.csv",index=False)
marketing.to_csv("marketing_features.csv",index=False)
products.to_csv("products_features.csv",index=False)
feedback.to_csv("feedback_features.csv",index=False)
order_items.to_csv("order_items_features.csv",index=False)

master_df.to_csv("master_dataset.csv",index=False)